import django.conf
import django.db.models.deletion
from django.db import migrations, models

class Migration(migrations.Migration):
    initial = True
    dependencies = [("auth", "0012_alter_user_first_name_max_length")]
    operations = [
        migrations.CreateModel(name="Branch", fields=[("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")), ("name", models.CharField(max_length=120)), ("address", models.CharField(max_length=240)), ("phone", models.CharField(blank=True, max_length=30)), ("delivery_fee", models.DecimalField(decimal_places=2, default=5000, max_digits=10)), ("is_active", models.BooleanField(default=True))], options={"ordering": ["name"]}),
        migrations.CreateModel(name="Category", fields=[("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")), ("name", models.CharField(max_length=80, unique=True)), ("description", models.CharField(blank=True, max_length=240)), ("is_active", models.BooleanField(default=True))], options={"ordering": ["name"], "verbose_name_plural": "categories"}),
        migrations.CreateModel(name="UserProfile", fields=[("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")), ("role", models.CharField(choices=[("customer", "Cliente"), ("operator", "Operador de sede"), ("kitchen", "Cocina"), ("courier", "Repartidor"), ("admin", "Administrador")], default="customer", max_length=20)), ("phone", models.CharField(blank=True, max_length=30)), ("branch", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="staff", to="orders.branch")), ("user", models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name="profile", to=django.conf.settings.AUTH_USER_MODEL))]),
        migrations.CreateModel(name="Product", fields=[("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")), ("name", models.CharField(max_length=120)), ("description", models.TextField(blank=True)), ("price", models.DecimalField(decimal_places=2, max_digits=10)), ("preparation_minutes", models.PositiveSmallIntegerField(default=20)), ("stock", models.PositiveIntegerField(default=0)), ("is_available", models.BooleanField(default=True)), ("branch", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="products", to="orders.branch")), ("category", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="products", to="orders.category"))], options={"ordering": ["category__name", "name"]}),
        migrations.CreateModel(name="Order", fields=[("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")), ("delivery_address", models.CharField(max_length=300)), ("notes", models.CharField(blank=True, max_length=500)), ("payment_method", models.CharField(choices=[("cash", "Efectivo"), ("card", "Tarjeta (simulada)"), ("transfer", "Transferencia (simulada)")], max_length=20)), ("status", models.CharField(choices=[("received", "Recibido"), ("preparing", "En preparación"), ("ready", "Listo para despacho"), ("on_the_way", "En camino"), ("delivered", "Entregado"), ("cancelled", "Cancelado")], default="received", max_length=20)), ("subtotal", models.DecimalField(decimal_places=2, max_digits=10)), ("delivery_fee", models.DecimalField(decimal_places=2, max_digits=10)), ("total", models.DecimalField(decimal_places=2, max_digits=10)), ("created_at", models.DateTimeField(auto_now_add=True)), ("updated_at", models.DateTimeField(auto_now=True)), ("branch", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="orders", to="orders.branch")), ("customer", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="orders", to=django.conf.settings.AUTH_USER_MODEL))], options={"ordering": ["-created_at"]}),
        migrations.CreateModel(name="OrderItem", fields=[("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")), ("product_name", models.CharField(max_length=120)), ("unit_price", models.DecimalField(decimal_places=2, max_digits=10)), ("quantity", models.PositiveSmallIntegerField()), ("order", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="items", to="orders.order")), ("product", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="order_items", to="orders.product"))]),
    ]
